routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('products', 'ProductsController')->except(['create', 'show', 'update']);

Route::post('add-category', 'ProductsController@addCategory')->name('add-category');
Route::get('get-products', 'ProductsController@getProducts')->name('get-products');

app/Products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Products extends Model
{
    use SoftDeletes;

    /**
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * relation between product and category
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function category(){
        return $this->hasOne(Category::class,'id','category_id');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Products;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ProductsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $product = new Products();
        $edit = false;
        $category_list = Category::pluck('name','id')->toArray();
        return view('products.index', compact('product','edit','category_list'));
    }

    /**
     * Add or Edit Product.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'quantity' => 'required',
            'category_id' => 'required',
            'price' => 'required|numeric',
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
        if ($validator->fails())
        {
            return redirect()->back()
                ->withInput()
                ->with('error',$validator->errors()->first());
        }

        $product_obj = Products::find($request->id); // Update Product
        $success_message = 'Product detail updated.';
        if(count((array)$product_obj) == 0){
            $product_obj = new Products(); // New Product
            $success_message = 'Successfully added a product';
        }

        $image_name = $product_obj->image;
        if($request->file('image')){
            $image = $request->file('image');
            $input['imagename'] = time().'.'.$image->getClientOriginalExtension();
            $destinationPath = public_path('/images');
            $image->move($destinationPath, $input['imagename']);
            $image_name = $input['imagename'];
        }

        $product_obj->image = $image_name;
        $product_obj->name = $request->get('name');
        $product_obj->price = $request->get('price');
        $product_obj->category_id = $request->get('category_id');
        $product_obj->is_active = ($request->is_active != null) ? 1 : 0;
        $product_obj->quantity = $request->get('quantity');

        if($product_obj->save()) {
            return redirect()->route('home')
                ->with('success', $success_message); // You may print this success message
        } else {
            return redirect()->back()
                ->withInput()
                ->with('error', 'Could not add a product');      // You may print this error message
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Products::find($id);
        if(count((array)$product) > 0){
            $edit = true;
            $category_list = Category::pluck('name','id')->toArray();
            return view('products.index', compact('product','edit','category_list'));
        } else {
            return redirect('/home')->with('error', 'Product not found');      // You may print this error message
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Products::find($id);
        if(count((array)$product) > 0){
            $product->delete();
            return redirect('/home')->with('success', 'Product deleted.');
        } else {
            return redirect('/home')->with('error', 'Product not found');      // You may print this error message
        }
    }

    /**
     * Add new category and return new category list
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function addCategory(Request $request) {
        $this->validate($request, [
            'name' => 'required|unique:category'
        ]);
        $category_obj = new Category();
        $category_obj->name = $request->name;
        $category_obj->save();
        $category_list = Category::pluck('name','id')->toArray();

        return response()->json(['status'=>'success','category_list' => $category_list]);
    }

    public function getProducts(Request $request){
        $sort_field_name = 'products.updated_at';
        $sort_type = 'asc';
        if(is_array($request->order) && count($request->order) > 0){
            $sort_array = ($request->order)[0];
            $sort_field_name = ($request->columns)[$sort_array['column']]['name'];
            $sort_type = $sort_array['dir'];
        }

        $search_string = null;
        $search_arr = $request->get('search',[]);
        if(isset($search_arr['value'])){
            $search_string = $search_arr['value'];
        }
        $product_list = [];

        $product_list_obj = Products::select(['products.*','category.name as category_name'])
            ->leftJoin('category as category','category.id','=','products.category_id')
            ->where(function($q) use ($search_string){
                if($search_string != null){
                    $q->orWhere('products.name','LIKE','%'.$search_string.'%');
                    $q->orWhere('products.price','LIKE','%'.$search_string.'%');
                    $q->orWhere('products.quantity','LIKE','%'.$search_string.'%');
                }
            });
             if($search_string != null) {
                 $product_list_obj->orWhereHas('category',function($qc) use ($search_string){
                     return $qc->where('category.name', 'LIKE', '%' . $search_string . '%');
                 });
             }
        ;

        $total_product = $product_list_obj->count();
        $product_list_data = $product_list_obj->skip($request->get('start',0))
            ->take($request->get('length',10))
            ->orderBy($sort_field_name,$sort_type)
            ->get()
        ;

        foreach($product_list_data as $product){
            $product_list[] = [
                ($product->image) ? '<img width="50px" height="50px" src="'.asset('images/'.$product->image).'">' : '',
                $product->name,
                $product->category_name,
                $product->price,
                $product->quantity,
                date('M d Y H:i A',strtotime($product->created_at)),
                '<a class="btn btn-success float-left mr-2" href="'.route('products.edit',$product->id).'"> Edit</a>'.
                '<form action="'.route('products.destroy',$product->id) .'" method="POST">'.
                method_field('DELETE').
                csrf_field().
                '<button class="btn btn-danger"> Delete</button></form>'

            ];
        }

        $response = [
            'draw'=>$request->draw,
            'recordsTotal' => $total_product,
            'recordsFiltered' => $total_product,
            'data' => $product_list
        ];
        return response()->json($response);
    }
}

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header col-md-12">
            <span>@if($edit) Product : {{$product->name}}@else New Product @endif</span>
            <span class="float-left mr-3">
              <a href="{{route('home')}}"><i class="fa fa-arrow-left"></i></a>
            </span>

            <span class="float-right">
              <button class="btn btn-success" data-toggle="modal" data-target="#CategoryModel">
                <i class="fa fa-plus"></i> Add category
              </button>
            </span>
          </div>

          <div class="card-body">
            @if (session('status'))
              <div class="alert alert-success" role="alert">
                {{ session('status') }}
              </div>
            @endif

            {!! Form::model($product, ['url' => route('products.store',$product->id), 'files' => true])  !!}
              @if($edit) {{ Form::hidden('id',$product->id) }} @endif
              <div class="form-group mb-3">
                <div class="col-md-6 float-left">
                  {!! Form::label('name', 'Name') !!}
                  {!! Form::text('name', $product->name, ['class' => 'form-control']) !!}
                </div>

                <div class="col-md-6 float-left">
                  {!! Form::label('price', 'Price') !!}
                  {!! Form::text('price', $product->price, ['class' => 'form-control']) !!}
                </div>
              </div>

              <div class="form-group">
                <div class="col-md-6 float-left">
                  {!! Form::label('quantity', 'Quantity') !!}
                  {!! Form::number('quantity', $product->quantity, ['class' => 'form-control']) !!}
                </div>

                <div class="col-md-6 float-left">
                  {!! Form::label('category_id', 'category') !!}
                  {!! Form::select('category_id', $category_list, $product->category_id, ['class' => 'form-control']) !!}
                </div>
              </div>
              <div class="clearfix mb-3"></div>
              <div  class="form-group">
                <div class="col-md-6 float-left">
                  {!! Form::label('image', 'Product Image') !!}
                  {!! Form::file('image', ['class' => 'image form-control']) !!}
                </div>
                @if($product->image)
                  <div class="image-wrapper d-inline-block text-center img-thumbnail">
                    <img src="{{asset('images/'.$product->image)}}">
                  </div>
                @endif
              </div>

              <div class="clearfix mb-3"></div>

              <div class="form-group col-md-12">
                <button class="btn btn-success" type="submit">@if($edit) Update Product @else Add Product @endif</button>
              </div>

              {!! Form::close() !!}

          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- New category model -->
  <div id="CategoryModel" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <span class="modal-title">New Category</span>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <div class="form-group mb-3">
            <div class="col-md-12 float-left">
              {!! Form::label('category_name', 'Category Name') !!}
              {!! Form::text('category_name', '', ['class' => 'form-control','required' => true]) !!}
              <div class="alert-danger" style="display: none;" id="cat_available_error" ><span>Category name is already available.</span></div>
            </div>
          </div>
          <div class="clearfix mb-3"></div>

          <div class="form-group col-md-12">
            <button class="btn btn-success" type="button" onclick="addCategory()">Add Category</button>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
@endsection

@section('scripts')
<script type="text/javascript">
  function addCategory() {
      let categoryName = $('#category_name').val();
      if(!categoryName){
          $('#category_name').addClass('has-error');

          $.notify("Category name is required!", "error");
          return false;
      }
      $.ajax('{{ route('add-category') }}',
          {
              type: 'POST',  // http method
              data: { name: categoryName, _token: '{{csrf_token()}}' },  // data to submit
              dataType: 'json', // type of response data
              timeout: 2000,     // timeout milliseconds
              success: function (data,status,xhr) {   // success callback function
                  $('#CategoryModel').modal('toggle');
                  $('#category_id').empty();
                  $.each(data.category_list, function( index, value ) {
                      $('#category_id').append($('<option>', {value:index, text:value}));
                  });
              },
              error: function (error) { // error callback
                $('#cat_available_error').show();
              }
          });
  }
</script>
@endsection